version: '2'
services:
  gitlab:
    container_name: "gitlab"
    image: 'gitlab/gitlab-ce:14.6.1-ce.0'
    restart: always
    privileged: true
    hostname: 'flower.gitlab.com'
    environment:
      TZ: 'Asia/Shanghai'
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'https://flower.gitlab.com'
        nginx['redirect_http_to_https'] = true
        letsencrypt['enable'] = false
        nginx['ssl_certificate'] = "/etc/ssl/nginx.pem"
        nginx['ssl_certificate_key'] = "/etc/ssl/nginx.key"
        gitlab_rails['gitlab_shell_ssh_port'] = 22
    ports:
      - '80:80'
      - '22:22'
      - '443:443'
    volumes:
      - ./config/ssl:/etc/ssl/
      - config:/etc/gitlab/
      - log:/var/log/gitlab
      - data:/var/opt/gitlab
volumes:
  log:
    driver: local
  data:
    driver: local
  config:
    driver: local