version: '2'
services:
  gitlab:
    container_name: "gitlab"
    image: 'gitlab/gitlab-ce:latest'
    restart: always
    privileged: true
    environment:
      TZ: 'Asia/Shanghai'
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'http://gitlab.flower.com:8100'
        gitlab_rails['gitlab_shell_ssh_port'] = 8101
    ports:
      - '8100:8100'
      - '8101:22'
      - '8102:443'
    volumes:
      - config:/etc/gitlab
      - log:/var/log/gitlab
      - data:/var/opt/gitlab
volumes:
  log:
    driver: local
  data:
    driver: local
  config:
    driver: local