version: '3.1'
services:
  mongo:
    container_name: mongo
    image: mongo
    restart: always
    environment:
      - TZ=Asia/Shanghai
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=111111
    ports:
      - 27017:27017
    volumes:
      - mongo:/data/db
      # - ./localtime:/etc/localtime
    networks:
      - some
  mongo-express:
    container_name: mongo-express
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: 111111
      ME_CONFIG_MONGODB_URL: mongodb://admin:111111@mongo:27017/
      ME_CONFIG_BASICAUTH: 'false'
    depends_on:
      - mongo
    networks:
      - some
volumes:
  mongo:
    driver: local
  log:
    driver: local
networks:
    some:
      external: true

