version: '3.3'
services:
  dtm:
    image: yedf/dtm:1.8
    container_name: dtm
    restart: always
    environment:
      IS_DOCKER: 1
      STORE_DRIVER: mysql
      STORE_HOST: mysql
      STORE_USER: root
      STORE_PASSWORD: root
      STORE_PORT: 3306
      TRANS_CRON_INTERVAL: 10
      RETRY_INTERVAL: 10
      TIMEOUT_TO_FAIL: 10
      MICRO_SERVICE_DRIVER: dtm-driver-gozero
      MICRO_SERVICE_TARGET: etcd://etcd1:2379/dtmservice
      MICRO_SERVICE_END_POINT: localhost:36790
    ports:
      - '36789:36789'
      - '36790:36790'
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    extra_hosts:
      - 'local.dtm.com:host-gateway'
    networks:
      - some
networks:
  some: 
    external: true 