version: "3"

services:
  jaeger:
    image: jaegertracing/all-in-one:1.26
    container_name: jaeger
    privileged: true
    # 解决时钟漂移带来的计算出正数的问题
    command: ["--query.max-clock-skew-adjustment=100ms"]
    # 选择网络
    networks:
      - some
    # 长久化，请抉择适宜本人的目录
    environment:
      SPAN_STORAGE_TYPE: badger
      BADGER_EPHEMERAL: ${BADGER_FLAG}
      BADGER_DIRECTORY_VALUE: /badger/data
      BADGER_DIRECTORY_KEY: /badger/key
    # badger存储在本地卷（或者映射到本地某个目录）
    volumes:
      - /data/storage/jaeger/badger:/badger
    #抉择端口
    ports:
      - 5775:5775/udp
      - 6831:6831/udp
      - 6832:6832/udp
      - 5778:5778
      - 16686:16686
      - 14250:14250
      - 14268:14268
      - 14269:14269
      - 9411:9411
    restart: always

networks:
  some: 
    external: true 