version: "3"

services:
  jaeger-collector:
    image: jaegertracing/jaeger-collector:1.28
    container_name: jaeger-collector
    ports:
      - "14269:14269"
      - "14268:14268"
      - "14267:14267"
      - "14250:14250"
      - "9412:9411"
    networks:
      - some
    restart: always
    environment:
      - SPAN_STORAGE_TYPE=elasticsearch
      - ES_SERVER_URLS=http://192.168.16.6:9200
      - LOG_LEVEL=debug

  jaeger-agent:
    image: jaegertracing/jaeger-agent:1.28
    container_name: jaeger-agent
    hostname: jaeger-agent
    ports:
      - "5775:5775/udp"
      - "6831:6831/udp"
      - "6832:6832/udp"
      - "5778:5778"
    networks:
      - some
    restart: always
    environment:
      - REPORTER_GRPC_HOST_PORT=jaeger-collector:14250
      - LOG_LEVEL=debug
    depends_on:
      - jaeger-collector

  jaeger-query:
    image: jaegertracing/jaeger-query:1.28
    container_name: jaeger-query
    restart: always
    environment:
      - SPAN_STORAGE_TYPE=elasticsearch
      - ES_SERVER_URLS=http://192.168.16.6:9200
      - LOG_LEVEL=debug
    ports:
      - "16686:16686"
    networks:
      - some

networks:
  some: 
    external: true 