version: '3.9'

services:
    prometheus:
        image: prom/prometheus:v2.31.1
        container_name: prometheus
        hostname: prometheus
        restart: always
        privileged: true
        volumes:
            - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
            - ./prometheus/node_down.yml:/etc/prometheus/node_down.yml
            - ./prometheus/targets.json:/etc/prometheus/targets.json
            - prometheusdata:/prometheus
        command:
            - '--config.file=/etc/prometheus/prometheus.yml'
            - '--storage.tsdb.path=/prometheus'
        ports:
            - "9090:9090"
        networks:
            - some

    alertmanager:
        image: prom/alertmanager:v0.23.0
        container_name: alertmanager
        hostname: alertmanager
        restart: always
        privileged: true
        volumes:
            - ./alertmanager/alertmanager.yml:/etc/alertmanager/alertmanager.yml
        ports:
            - "9093:9093"
        networks:
            - some

    grafana:
        image: grafana/grafana:8.2.4-ubuntu
        container_name: grafana
        hostname: grafana
        privileged: true
        restart: always
        volumes:
            - grafanadata:/var/lib/grafana
        ports:
            - "3001:3000"
        networks:
            - some

    node-exporter:
        image: quay.io/prometheus/node-exporter
        container_name: node-exporter
        hostname: node-exporter
        restart: always
        ports:
            - "9100:9100"
        networks:
            - some

volumes:
    prometheusdata:
        driver: local
    grafanadata:
        driver: local
networks:
    some:
        external: true 

