version: '3'
services: 
  redis1:
    container_name: redis1
    image: redis:6.0
    restart: always
    privileged: true
    ports:
      - '6360:6360'
    volumes:
      - redis_logs1:/data/logs
      - ./conf/redis1.conf:/usr/local/etc/redis/redis.conf
    command:
      "redis-server /usr/local/etc/redis/redis.conf"
    networks:
      - consistency
  redis2:
    container_name: redis2
    image: redis:6.0
    restart: always
    privileged: true
    ports:
      - '6361:6361'
    volumes:
      - redis_logs2:/data/logs
      - ./conf/redis2.conf:/usr/local/etc/redis/redis.conf
    command:
      "redis-server /usr/local/etc/redis/redis.conf"
    networks:
      - consistency
  redis3:
    container_name: redis3
    image: redis:6.0
    restart: always
    privileged: true
    ports:
      - '6362:6362'
    volumes:
      - redis_logs3:/data/logs
      - ./conf/redis3.conf:/usr/local/etc/redis/redis.conf
    command:
      "redis-server /usr/local/etc/redis/redis.conf"
    networks:
      - consistency
volumes:
  redis_logs1:
    driver: local
  redis_logs2:
    driver: local
  redis_logs3:
    driver: local
networks:
  consistency:
    driver: bridge