version: '2'
services:
  nginx:
    container_name: "nginx"
    image: 'nginx:1.23.1'
    restart: always
    privileged: true
    environment:
        - TZ=Asia/Shanghai  # 这里的设置的时区会影响log里面的时间
        - NGINX_HOST=foobar.com
        - NGINX_PORT=3080
    ports:
        - '80:80'
    volumes:
        - type: bind
          source: ./conf/nginx.conf
          target: /etc/nginx/nginx.conf
        - ./conf/conf.d:/etc/nginx/conf.d
        - ./www:/usr/local/www
    networks:
      - some
networks:
    some:
      driver: bridge