version: '3'
services:
   # redis
  redis:
    container_name: ubuntu20
    image: ubuntu:20.04
    privileged: true
    command: tail -f /dev/null
    volumes:
      - ./init.sh:/root/init.sh
    networks:
      - some
networks:
    some:
      external: true
