version: '3'
services:
   # redis
  redis:
    container_name: mysql-exporter
    image: prom/mysqld-exporter:v0.13.0
    restart: always
    privileged: true
    ports:
      - 9104:9104
    environment:
      -  DATA_SOURCE_NAME=root:root@(mysql:3306)/
    networks:
      - default 
      - some

networks:
    some:
      external: true
