version: '3'
services:
  jenkins:
    image: 'jenkins/jenkins:lts'
    container_name: jenkins
    restart: always
    privileged: true
    environment:
      - TZ=Asia/Shanghai
    ports:
      - '8110:8080'
      - '8111:50000'
    volumes:
      - /etc/localtime:/etc/localtime
      - home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/bin/docker:/usr/bin/docker
      - /usr/lib/x86_64-linux-gnu/libltdl.so.7:/usr/lib/x86_64-linux-gnu/libltdl.so.7
    networks:
      - some
volumes:
  home:
    driver: local
networks:
    some:
     driver: bridge