filebeat.inputs:
 
- type: log
  enabled: true
  paths:
    - /tools/logs/*.log
  fields:
    logfrom: boot-zipkin
  multiline.pattern: '^[[:space:]]|^Caused by:'
  multiline.negate: false
  multiline.match: after
 
output.logstash:
  hosts: ["logstash:5044"]
 
processors:
  - add_host_metadata: ~
  - add_cloud_metadata: ~
  - add_docker_metadata: ~
  - add_kubernetes_metadata: ~