version: '3'
services:
  # mysql
  mysql:
    container_name: mysql
    image: mysql:5.7
    restart: always
    environment:
      - TZ=Asia/Shanghai"
      - MYSQL_DATABASE='some'
      - MYSQL_USER='root'
      - MYSQL_PASSWORD='root'
      - MYSQL_ROOT_PASSWORD='root'
      - MYSQL_ALLOW_EMPTY_PASSWORD='true'
    ports:
      - '3306:3306'
    volumes:
    - mysql_data:/var/lib/mysql
    - ./mysql/my.cnf:/etc/my.cnf:rw
    networks:
      - some
  # redis
  redis:
    container_name: redis
    image: redis:6.0
    restart: always
    ports:
      - '6379:6379'
    volumes:
      - ./redis/redis.conf:/etc/redis/redis.conf:rw
volumes:
    mysql_data:
        driver: local
networks:
    some:
     driver: bridge
    
