# my global config
global:
  scrape_interval: 15s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  evaluation_interval: 15s # Evaluate rules every 15 seconds. The default is every 1 minute. # scrape_timeout is set to the global default (10s).
  external_labels:
    monitor: 'codelab-monitor'
  query_log_file: /prometheus/query.log

# Alertmanager configuration
alerting:
  alertmanagers:
    - static_configs:
        - targets:
          # - alertmanager:9093

# Load rules once and periodically evaluate them according to the global 'evaluation_interval'.
rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"
  - 'prometheus.rules.yml'
  - 'prometheus.alerting.rules.yml'
  - 'node_down.yml'

# A scrape configuration containing exactly one endpoint to scrape:
# Here it's Prometheus itself.
scrape_configs:
  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
  - job_name: "prometheus"
    scrape_interval: 5s
    # metrics_path defaults to '/metrics'
    # scheme defaults to 'http'.

    static_configs:
      - targets: ["172.17.0.1:9090"]

  - job_name: "jaeger"
    static_configs:
      - targets: ["192.168.99.103:14269", "192.168.99.103:16687", "192.168.99.103:14271"]

  - job_name: "etcd"
    static_configs:
      - targets: ["172.17.0.1:2379", "172.17.0.1:2378", "172.17.0.1:2376"]

  - job_name: "redis-exporter"
    static_configs:
      - targets: ["172.17.0.1:9121"]

  - job_name: "mysql-exporter"
    static_configs:
      - targets: ["172.17.0.1:9104"]

  - job_name: node
    static_configs:
    - targets: ['172.17.0.1:9100']

  - job_name: 'dxyp'
    file_sd_configs:
    - files:
      - targets.json